Shopify/shopify-api-ruby

Gemfile
Gemfile.lock
Gemfile_ar31
Gemfile_ar32
Gemfile_ar40threadsafe
Gemfile_ar42threadsafe
README.md
shopify_api.gemspec
test/recurring_application_charge_test.rb

This is just to verify that the gem is still working, once
https://github.com/Shopify/activeresource/pull/2 is merged
this will either point to that resulting ref or to the gem
when it gets released on rubygems.
Please review @boourns @benjlcox 
/cc @chrisbutcher @peterjm

Uses the threadsafe branch with threadlocals

---

Gemfile.lock
lib/shopify_api/version.rb

All the deps are gone and we need to release a new gem.
Please review @camilo

bump shopify version

---

lib/shopify_api/session.rb
test/session_test.rb

Changed signature validation to HMAC-SHA256 per API change

Changed signature validation to HMAC-SHA256 per API change

---

lib/shopify_api/resources/gift_card.rb
test/fixtures/gift_card.json
test/fixtures/gift_card_disabled.json
test/gift_card_test.rb

This adds `GiftCard` resource which is basic CRUD and a `disable` method.
@csaunders

Add GiftCard resource

---

CHANGELOG
Gemfile.lock
lib/shopify_api/version.rb

/review @csaunders, @ilikeorangutans

Bump to v4.0.1

---

CHANGELOG
lib/shopify_api/version.rb

version bump to 4.0.7

---

lib/shopify_api/resources/tax_service.rb
test/fixtures/tax_service.json
test/tax_service_test.rb

Add tax service files

---

lib/shopify_api/resources/fulfillment.rb
test/fulfillment_test.rb

@kevinhughes27 Adds the ability to open a fulfillment.

Adds ability to open a fulfillment.

---

lib/shopify_api/resources/refund.rb
test/fixtures/refund.json
test/refund_test.rb

/cc @andrewpaliga @ch33sybr3ad

Add Refund files

---

README.md

**Background:** 
* For somebody who is completely new to Shopify or somebody who isn't quite sure how to create a new app or generate the required credentials, a link that guides one on how to go about the same could be handy.

Add link to help setup app and generate required credentials in README

---

.travis.yml

I don't believe we're still using Flowdock for anything, are we?
@kevinhughes27 @maartenvg

Remove Flowdock notifications

---

CHANGELOG
lib/shopify_api/version.rb

Bumps version to 4.2.1.
@girasquid @kevinhughes27

Bumps version to 4.2.1

---

CHANGELOG
lib/shopify_api/version.rb

Bump the version number so I can push a new release
@kevinhughes27 @garethson for review

Bump version to 4.2.2

---

README.md

@peterjm does this make sense?

Update README Threadsafety section

---

Rakefile
shopify_api.gemspec

Some further cleanup/improvements before https://github.com/Shopify/shopify_api/pull/280.
This mainly cleans up dependencies but also a few minor updates for things no longer required in Ruby 2+.
@peterjm @kevinhughes27

Gemspec cleanup

---

README.md

Add Rails 5 usage note to README

---

lib/shopify_api/resources/application_credit.rb
test/application_credit_test.rb
test/fixtures/application_credit.json
test/fixtures/application_credits.json

- adds application credits resource to shopify_api
@Shopify/finance @kevinhughes27 @swalkinshaw

application credit resource

---

README.md

Add SVG gem-version metadata badge from [Shields.io](http://shields.io) to visually denote latest gem version.

Add gem-version badge to README

---

lib/shopify_api/resources/storefront_access_token.rb
test/fixtures/storefront_access_token.json
test/fixtures/storefront_access_tokens.json
test/storefront_access_token_test.rb

👀  @Shopify/channels-dev-pod, @Shopify/api-documentation, @Shopify/api

Added StorefrontAccessToken to the gem

---

lib/shopify_api/resources/customer_saved_search.rb
test/customer_saved_search_test.rb

Fix the endpoint for CustomerSavedSearch#customers

---

lib/shopify_api/resources/marketing_event.rb
test/fixtures/marketing_event.json
test/fixtures/marketing_events.json
test/marketing_event_test.rb

closes https://github.com/Shopify/merchant-marketing/issues/361

Add Marketing Events resource

---

CHANGELOG
lib/shopify_api/resources/report.rb
lib/shopify_api/version.rb
test/fixtures/report.json
test/fixtures/reports.json
test/report_test.rb

Add support for Report Publishing API

---

CHANGELOG
lib/shopify_api/version.rb

Bumping the version before releasing a new gem.

Bump gem to version 4.7.0

---

README.md

Fixes https://github.com/Shopify/shopify_api/issues/336
@jordanliddle @kristinaelise 👀

Clarify session instantiation in README

---

lib/shopify_api/resources/discount_code.rb
lib/shopify_api/resources/price_rule.rb
test/discount_code_test.rb
test/fixtures/discount_code.json
test/fixtures/discount_codes.json
test/fixtures/price_rule.json
test/fixtures/price_rules.json
test/price_rule_test.rb

Adding support for price rules and discount codes

Adds support for price rules

---

CHANGELOG
lib/shopify_api/version.rb

Bump gem to version 4.9.0

---

README.md

Updating the first link to point to the developers portal, and the second description to accurately reflect the link location.

Updating two links

---

CHANGELOG
lib/shopify_api/version.rb

Added `ShopifyAPI::AccessScope`

Bump gem version to 4.10.0

---

CHANGELOG
lib/shopify_api/version.rb

Version release with the new inventory level apis 
@celsodantas

packaging for release 4.11.0

---

README.md

Referring to #439.
Running `rake test` were failing. To overcome that, I had to run `bundle exec rake`, just as it is on the CI.

Add more details to "Using Development Version"

---

.travis.yml
CHANGELOG
README.md
lib/shopify_api/resources/graphql.rb
lib/shopify_api/version.rb
shopify_api.gemspec

Support for the new GraphQL Admin API 🎉 
https://help.shopify.com/api/graphql-admin-api

Add support for the GraphQL Admin API

---

.gitignore
lib/shopify_api/resources/collection_publication.rb
lib/shopify_api/resources/product_publication.rb
lib/shopify_api/resources/publication.rb
test/collection_publication_test.rb
test/fixtures/collection_publication.json
test/fixtures/collection_publications.json
test/fixtures/product_publication.json
test/fixtures/product_publications.json
test/fixtures/publications.json
test/product_publication_test.rb
test/publication_test.rb

Add support for the Publication, ProductPublication, and CollectionPublication resources.

Add support for Publication APIs

---

CHANGELOG
lib/shopify_api/version.rb

Updated the changelog and the version number.

Packaging for version 5.2.0

---

.gitignore
CHANGELOG
lib/shopify_api/version.rb

Also ignoring a few local folders that appear when running `bundle install`.

Packaging for release v5.2.1

---

CHANGELOG
lib/shopify_api/version.rb

Update version number to version 5.2.2.

Packaging for release v.5.2.2

---

test/product_test.rb

Added tests for the `price_range` method of `Product` class

Added price_range test

---

CHANGELOG
lib/shopify_api/version.rb

Changeset: https://github.com/Shopify/shopify_api/compare/v5.2.4...3de3a6a9fd01d062e0bb6ae662e98e9e9f0e41a0

Packaging for release 6.0.0

---

CHANGELOG
README.md
lib/shopify_api/version.rb

Update version and readme for 7.0.0 release

Setup for version 7

---

CHANGELOG
lib/shopify_api/api_version.rb

- add api release version
- update change log for release.

Package for version 7.0.0

---

CHANGELOG.md
README.md
lib/shopify_api/version.rb

Updated readme, changelog and packaging for release.

packaging for release 8.0.0

---

lib/active_resource/detailed_log_subscriber.rb

fixes #589 
This will allow ruby 2.1 to still be supported.

Small ruby compat fix

---

CHANGELOG.md

There were a few missing PRs that weren't added to the Changelog.

Package release for 8.1.0

---

CHANGELOG.md
lib/shopify_api/version.rb

Some README files were modified by the other commits. The only change in the code is this PR: https://github.com/Shopify/shopify_api/pull/693.

Package for release 9.0.2

---

README.md

Require the gem in installation

---

CHANGELOG.md
lib/shopify_api/version.rb

Update to 9.0.3. 
Includes changes for #655, #701, and #700.

Package for release 9.0.3

---

shopify_api.gemspec

This is now required for our gem deploy

Update allowed_push_host in gemspec

---

docs/graphql.md

Fixes https://github.com/Shopify/shopify_api/issues/723

Update dead link to point to correct ID

---

docs/index.md

Update docs year to 2020

---

README.md

Since this in in a `code` block, the markdown doesn't render.

Fix markdown in comment

---

Rakefile
docs/index.md
lib/verify_docs.rb

Prevent README and public docs inconsistencies

---

service.yml

Part of Shopify/shopify#258083

Prepare for api-patterns-team channel rename

---

.rubocop_todo.yml
lib/shopify_api/metafields.rb
lib/shopify_api/resources/fulfillment_order.rb
lib/shopify_api/resources/fulfillment_v2.rb
lib/shopify_api/resources/inventory_level.rb
test/fulfillment_order_test.rb
test/fulfillment_test.rb
test/fulfillment_v2_test.rb
test/marketing_event_test.rb
test/meta_test.rb

This is likely the last of the auto-corrects for cops - the cop with the most offenses now is 24 which begins to be manageable manually.

Fix rubocop trailing hash comma cop

---

README.md

This PR just adds a notice to the README file to make it easier for folks to find the current documentation until we release the new version.

Add notice about v9 to the README

---

README.md

This PR adds back the log of breaking changes, along with some information for the upcoming new version.

Add back breaking change log

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Packaging for release v10.0.3
* Checked the pipeline is green.
* Checked this version out in a local instance and manually verified.
(Courtesy of @ryaanwells - copy of closed PR #940)

Packaging for release 10.0.3

---

CHANGELOG.md

Add pointer to API changelog

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Packaging for release 11.0.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

bump version 12.1.0

---

README.md

[docs] Fix links for offline/online access

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Packaging for release v12.2.0

---

README.md

Improving reading/"scan-ability" for docs

Improving getting started docs for "scan-ability"

---

docs/usage/oauth.md

Improve Performing OAuth/Session documentation
- [New OAuth docs](https://github.com/Shopify/shopify-api-ruby/blob/2543e40c519b5c784c3b9668ce36c68ff8c408f2/docs/usage/oauth.md)
- [Previous OAuth docs](https://github.com/Shopify/shopify-api-ruby/blob/77ab36ca816516a677b736a46eec59aeed36a055/docs/usage/oauth.md)

Improve "Performing OAuth"/Session documentation

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Packaging for release 14.1.0

---

CHANGELOG.md
lib/shopify_api/auth/session.rb
test/auth/session_test.rb

Adding this method to support changes in https://github.com/Shopify/shopify_app/pull/1822
Added a unit test.

Add `Session#copy_attributes_from` method

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Package for release - 14.3.0
N/A

Packaging for release 14.3.0

---

Gemfile.lock

We have been seeing flaky deploys with our pipeline.
We have been instructed to updated our bundler version to resolve this.
```
gem install bundler
bundle update --bundler --conservative  
```

Update bundler, to stop flaky deploys

---

docs/usage/oauth.md

- Fixes https://github.com/Shopify/develop-app-access/issues/291
Added docs on using the TokenExchange API

Add token exchange API docs

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

This PR sets up for the release of v14.4.0

Packaging for release v14.4.0

---

docs/usage/webhooks.md

Fixes [this comment](https://github.com/Shopify/shopify-api-ruby/issues/1328#issuecomment-2239101679).

Update webhook handler docs

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

This PR sets up for the release of v14.5.0.

Packaging for release v14.5.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Packaging for release 14.6.0

---

.github/workflows/close-waiting-for-response-issues.yml

14 days matches what we use in the JS repos

Update number of inactive days before closing tickets

---

CHANGELOG.md
Gemfile.lock
lib/shopify_api/version.rb

Release 14.11.0
