Shopify/shopify-api-ruby

- Gemfile.lock
- shopify_api.gemspec
Pry and thor bring along a bunch of "friends"  if they slip into a production
bundle it seems  unlikely that either is needed in production, moving them here
to be a dev dependency.
@kevinhughes27 @jamesmacaulay @ibawt makes sense?
> Move pry and thor to dev dependencies

- lib/shopify_api/resources/shop.rb
- test/shop_test.rb
This allows options to be passed when fetching the current shop.  For example
ShopifyAPI::Shop.current(params: { fields: ['name', 'email'] })
> Allow options to be passed to shop fetching

- lib/shopify_api/resources/o_auth.rb
- test/fixtures/o_auth_revoke.json
- test/o_auth_test.rb
We don't provide an easy way to revoke an OAuth token.
OAuth tokens can be revoked with `ShopifyAPI::OAuth.revoke` .
/related Shopify/facebook-commerce#2765
/review @awd, @ilikeorangutans
> Add support for token revocation

- lib/shopify_api/session.rb
- test/session_test.rb
@clayton-shopify & @kevinhughes27 
This is an extra precaution to make sure requests always go to a .myshopify.com domain.
For development, there is still a ShopifyAPI::Session.myshopify_domain class variable that can be modified outside of the production environment.
> Add a myshopify_domain class variable to use for building the site url.

- lib/shopify_api/session.rb
- shopify_api.gemspec
- test/session_test.rb
@csaunders & @clayton-shopify for review
This implements the same escaping that we added in Shopify for generating the signature to prevent delimiters from being added to tamper with params without changing the signature.  In the uncommon cases where these delimiters do appear in the keys or values, this pull request will make sure the signature is properly validated.
> Escape ampersand in params or equal in keys before signing with hmac.

- README.md
Updating the README to include new security features, namely the state and required redirect_uri.
Also updated the bit about the ``shopify`` executable, since it's now a separate gem.
@ilikeorangutans @awd
> Updating README to include new security features

- lib/shopify_api/resources/fulfillment_event.rb
- test/fixtures/fulfillment_event.json
- test/fulfillment_event_test.rb
This PR adds support to fulfillment events. Fulfillment events are simple resources that can be CRUDed under `/admin/orders/:order_id/fulfillments/:fulfillment_id/events`.
Please review @christianblais @csaunders
> Add support to fulfillment events

- lib/active_resource/json_errors.rb
- test/active_resource/json_errors_test.rb
The fix in https://github.com/Shopify/shopify_api/pull/107 was wrong IMO. As the documentation states, `attribute should be set to :base if the error is not directly associated with a single attribute.`
@kevinhughes27 @maartenvg
> String errors should be added to :base

- lib/shopify_api/resources/shipping_zone.rb
- test/fixtures/shipping_zones.json
- test/shipping_zone_test.rb
We moved everyone over to shipping zones, and it has made all the rates that are showing on the countries resource invalid.
I have a PR on shopify's side to add the shipping zone endpoint, this adds the resource.
@shawnfrench @csaunders
> Add shipping zone resource

- lib/shopify_api/resources/recurring_application_charge.rb
- lib/shopify_api/resources/usage_charge.rb
- test/fixtures/recurring_application_charge.json
- test/fixtures/recurring_application_charge_adjustment.json
- test/fixtures/usage_charge.json
- test/fixtures/usage_charges.json
- test/recurring_application_charge_test.rb
- test/usage_charge_test.rb
- adds usage charge resource to shopify api
https://github.com/Shopify/shopify/pull/56192/files
@Shopify/finance @dominiquesr @Not-Jake
> adding usage charge resource

- lib/shopify_api/version.rb
- bump gem to 4.1.0, can't deploy without changing version number
@Shopify/finance @dominiquesr
> bump gem to 4.1.0

- CHANGELOG
- lib/shopify_api/resources/base.rb
- lib/shopify_api/version.rb
@maartenvg @celsodantas @peterjm 
Closes #225
There is not default timeout on `ShopifyAPI::Base` (it's `nil` 😔). This introduces a ~~25~~ 90 second default timeout for API requests.
> Add default timeout to ShopifyAPI::Base

- .travis.yml
- CHANGELOG
- Gemfile_ar50
- lib/shopify_api/resources/base.rb
- lib/shopify_api/version.rb
- test/base_test.rb
- test/recurring_application_charge_test.rb
@alexaitken @kevinhughes27 @ch33sybr3ad
Fixes https://github.com/Shopify/shopify_api/issues/194
`ShopifyAPI::Base.headers` behaves differently, depending on whether we've detected that we're using the threadsafe version of ActiveResource, or the non-threadsafe version of ActiveResource.
Right now, we're detecting that based on the version number of the `activeresource` gem. This isn't a sustainable solution, because:
1. It assumes that the "pre" string is "threadsafe", which is only defined in Shopify's fork of ActiveResource. Now that core ActiveResource contains the threadsafe changes, we should start to work with that instead of just our own fork.
2. It only works with major version 4, and core ActiveResource is now at version 5
Instead of detecting the version string, directly check …
> Better detection of threadsafe ActiveResource

- lib/shopify_api/resources/fulfillment.rb
- test/fulfillment_test.rb
This pull request resolve #253 issue add missing `order_id` prefix_option.
> Add missing order_id prefix_option to Fulfillment resource

- lib/shopify_api/resources/customer.rb
- test/customer_test.rb
- test/fixtures/customers.json
- test/fixtures/customers_account_activation_url.json
According to the [API Announcements](https://ecommerce.shopify.com/c/api-announcements/t/new-api-to-retrieve-customer-account-activation-urls-305726) post.
I updated the gem with the new `account_activation_url` method for Customers resource.
/cc @kevinhughes27
> Add Customer#account_activation_url method

- lib/shopify_api/resources/access_token.rb
- test/access_token_test.rb
- test/fixtures/access_token_delegate.json
Adds the `/admin/access_tokens/delegate` endpoint. The endpoint is documented here: https://help.shopify.com/api/guides/authentication/oauth (or will be after the documentation is deployed next).
@garethson @kevinhughes27 for review
> Add ability to delegate an access token

- CHANGELOG
- lib/shopify_api/version.rb
- shopify_api.gemspec
Does `4.3.0` make sense for the version bump?
@peterjm  @kevinhughes27
> Bump to version 4.3.0

- lib/active_resource/connection_ext.rb
- lib/shopify_api.rb
- lib/shopify_api/connection.rb
This PR attempts to improve on #286 by only setting `ActiveResource::Base.connection_class` if it is available, and falls back to monkeypatching `ActiveResource::Connection` for older versions of `activeresource` that do not have that feature.
> use a custom subclass of ActiveResource::Connection if possible

- lib/shopify_api/countable.rb
- test/countable_test.rb
The `Countable` mixin doesn't work with activeresource@master because of this pull request that was merged in January: rails/activeresource#96. This PR adds a test to expose this issue as well as a fix.
In short, the problem is that the call to `get(:count)` now no longer removes the root from the response properly, so the return value is now `{"count" => 16}` instead of `16` (assuming there are 16 of the resource). To fix it, I added some code to check if the value returned from `get(:count)` is a Hash instead of a number, and remove the root manually. I've also posted a comment on the offending PR about the new problem it caused here: https://github.com/rails/activeresource/pull/96#issuecomment-234991786
> Fix for `TypeError: can't convert Hash into Integer` when calling `Product.count` with latest activeresource

- lib/shopify_api/resources/fulfillment_request.rb
- test/fulfillment_request_test.rb
Adds the ability to mark a fulfillment request as failed.
@kwestein @shilpasequeira @t6d @mikeletscher 
cc @kevinhughes27
> Add ability to mark a fulfillment request as failed.

- lib/active_resource/disable_prefix_check.rb
For some reason we are patching this module in ActiveResource and in the actual gem the prefix args are optional (https://github.com/rails/activeresource/blob/f8abaf13174e94d179227f352c9dd6fb8b03e0da/lib/active_resource/base.rb#L1575), but in our version they are required.  This fix makes them optional so this error doesn't happen:
```ruby
ShopifyAPI::ProductListing.find(:first, params: {application_id: KEYS[:shopify_provider_id]})
ArgumentError: wrong number of arguments (given 0, expected 1)
        from /Users/matt/.gem/ruby/2.3.1/gems/shopify_api-4.3.0/lib/active_resource/disable_prefix_check.rb:15:in `block in conditional_prefix'
          from /Users/matt/.gem/ruby/2.3.1/bundler/gems/activeresource-f8abaf13174e/lib/active_resource/base.rb:1575:in `create_resource_for'
```
/review …
> Remove required argument on prefix in disable_prefix_check

- test/refund_test.rb
Just a tiny little thing
```RUBY
refund = ShopifyAPI::Refund.create(
:order_id => 450789469,
:restock => true,
:note => "wrong size",
:shipping => { :full_refund => true },
:refund_line_items => [{ :line_item => 518995019, :quantity => 1 }] # Here is the culprit
)
refund = ShopifyAPI::Refund.create(
:order_id => 450789469,
:restock => true,
:note => "wrong size",
:shipping => { :full_refund => true },
:refund_line_items => [{ :line_item_id => 518995019, :quantity => 1 }] # Tiny little change
)
```
It doesn't break the test, but it wouldn't work with the shopify API, since the parameter has to be either a line_item json  including the id `{ "id": 123123,  ... }`, or the line_item_id.
Kinda bit me, since I usually use the tests as a kind of documentation ;)
> Fix refund_test create params

- CHANGELOG
- lib/shopify_api/version.rb
- bumping gem version to 4.3.1 for releasing support for application credits
@Shopify/finance @kevinhughes27 @peterjm
> Bump to version 4.3.1

- lib/shopify_api/resources/base.rb
- test/base_test.rb
@kevinhughes27 @maartenvg 
when you set `site=` in `ActiveResource::Base`, it parses out the password and username out of that and sets it internally. so when we clear the session here, we should also clear those flags, otherwise you end up with unexpected authentication headers down the line
> Unexpected Auth headers is so Basic

- .travis.yml
- Gemfile
- Gemfile_ar30
- Gemfile_ar31
- Gemfile_ar32
- Gemfile_ar40
- Gemfile_ar_master
- shopify_api.gemspec
`shopify_api` doesn't need anything more recent than `MRI 2.0`, so might as well not be too restrictive there.
Feel free to bump that requirement as needed later, but I think it's better that way for now.
@swalkinshaw @camilo
> Relax ruby version requirement to 2.0

- README.md
- lib/shopify_api/session.rb
- shopify_api.gemspec
- test/fulfillment_request_test.rb
- test/session_test.rb
This adds documentation on how to use this gem with a per-user access token. It exposes `expires_in`, `expires_at` and `expired?` which can be called when the `extra` hash is populated in `ShopifyAPI::Session`. The intended use for this `extra` hash is that the caller will populate it with the data that Shopify provides, to have it available through the entire lifetime of the session. A few apps serialize the `ShopifyAPI::Session` object so it is a good place to store this information.
@clayton-shopify @ilikeorangutans @Shopify/api
> Adding code and tests for online-mode access tokens

- lib/shopify_api/resources/fulfillment_request.rb
- test/countable_test.rb
- test/fulfillment_request_test.rb
- test/fulfillment_test.rb
- test/limits_test.rb
- test/session_test.rb
- test/test_helper.rb
- test/transaction_test.rb
In the test helper we generated the wrong test method name in the `def test` helper, meaning that all tests defined with the `should` or `test` methods weren't actually run. On top of that, because the setup method is an actual method that is overridden from the base class, we need to call `super` to ensure the base-setup is still performed properly. Since that setup sets global vars, most randomized runs will start with a test that will setup these globals correctly for the duration of the entire test-suite. But once in a while a badly setuo test will run first, failing because the base setup steps are not executed.
In this PR:
- Use `_` instead of `:` in generated test names forcing them to be run
- Use better teardown of globals in test helper to surface problems of leaking state …
> Actually run all tests and remove flakiness by doing proper setup and teardown

- CHANGELOG
- lib/shopify_api/resources/base.rb
- lib/shopify_api/resources/resource_feedback.rb
- lib/shopify_api/version.rb
- test/resource_feedback_test.rb
Add ResourceFeedback and bump gem version to 4.3.8
Issue: https://github.com/Shopify/product-publishing-feedback/issues/193
> Add ResourceFeedback and Bump Version to 4.3.8

- lib/shopify_api/resources/resource_feedback.rb
- lib/shopify_api/version.rb
- test/resource_feedback_test.rb
Singularize ResourceFeedback `collection_name`, to coincide with API path change to rename endpoint to `/admin/resource_feedback`
> Singularize ResourceFeedback collection_name

- CHANGELOG
- lib/shopify_api/resources/customer.rb
- lib/shopify_api/resources/customer_invite_message.rb
- lib/shopify_api/version.rb
- test/customer_test.rb
- test/fixtures/customer_invite.json
Adds `ShopifyAPI::CustomerInvite` and exposes `Customer#send_invite`
> Add support for customer invites

- lib/shopify_api/resources/collection_listing.rb
- lib/shopify_api/resources/product_listing.rb
- test/collection_listing_test.rb
- test/product_listing_test.rb
We've deprecated the endpoint in Shopify that took an application id as part of the URL, because the application can be assumed from the context of the request.
This changes our Ruby library to reflect these changes.
> Remove application_id param from listing endpoints

- CHANGELOG
- lib/shopify_api/resources/collection_listing.rb
- lib/shopify_api/resources/product_listing.rb
- test/collection_listing_test.rb
- test/product_listing_test.rb
The listing classes were broken, because they were trying to use the `id` field as a primary key, which doesn't exist for listings. This tells ActiveResource to use the underlying object id as the primary key.
This was the reason the URL for fetching the product ids for collections was "/admin/collection_listings//123/product_ids.json" (note the double "//") -- ActiveResource was trying to fill in an id between the slashes, but just ended up rendering an empty string (`nil.to_s`)
> Fix bug with listing classes

- CHANGELOG
- lib/shopify_api/metafields.rb
- lib/shopify_api/resources/shop.rb
- lib/shopify_api/version.rb
- test/draft_order_test.rb
- test/fixtures/metafields.json
- test/product_test.rb
- test/shop_test.rb
Fixes https://github.com/Shopify/shopify_api/issues/215.
This allows passing URL parameters to the [Metafields API](https://help.shopify.com/api/reference/metafield#index).
Example Request:
`my-shop.myshopify.com:443/admin/<collection_name>/:collection_id/metafields.json?limit=250&page=1`
> Metafield URL Parameters

- lib/shopify_api/resources/engagement.rb
- lib/shopify_api/resources/marketing_event.rb
- test/fixtures/engagement.json
- test/marketing_event_test.rb
Hey Shopify team!
With the new announcement, and 1.0, of the Marketing Events API we are about to starting using it at Sweet Tooth to show real engagement statistics to merchants. 
As documented, marketing events have associated engagements which track views, clicks, etc. The endpoint is as follows:
Right now there is no official support for engagement via this gem. And ideally, for best practice, we want to avoid directly using `ActiveResource` REST methods from within our codebase. This PR introduces a small wrapper, that allows us to nicely create engagements. 
The specs are included as well.
> Add support for marketing event engagements

- CHANGELOG
- lib/shopify_api/version.rb
Bumping the version for `ShopifyAPI::MarketingEvent.add_engagements`
> Bump Gemfile version to 4.8.0

- README.md
> Fix link to Shopify API reference

- README.md
Now that Active Resource 5.0 is out with Rails 5 support, there is no need for special Rails 5 instructions.
> Remove unneeded Rails 5 instructions

- lib/shopify_api/limits.rb
Shopify Plus plans have double the API request limit of non-plus plans (bursts of 80 requests as opposed to 40 with the regular plans).
Prior to the changes made below, if `@api_credit_limit[:shop]` was initialized with the response from a Shopify Plus shop, then subsequent calls to `credit_limit` would always return 79 regardless of whether or not the shop had the higher request limit. Since `credit_left` uses `credit_limit`, requests made to non-Plus shops could be made under the pretense that they had more requests remaining than they actually did, triggering 429 errors in the process. 
The changes in this pull request prevent setting a global request limit by calculating the credit limit for each shop as part of each request/response cycle.
> Calculate credit_limit per shop

- lib/shopify_api/resources/line_item.rb
- test/fixtures/order_with_properties.json
- test/order_test.rb
We are seeing an error where `ActiveResource` tries to (incorrectly) create a resource to load an order's line_item property hash value. The workaround in this PR is to rescue the `NameError` and return the attributes as a hash (and not a resource).
> Fetch order with custom properties

- lib/shopify_api/resources/access_scope.rb
Added `AccessScope` to the ShopifyAPI in https://github.com/Shopify/shopify/pull/145004 via `test/api/unit/access_scope_api_test.rb`, but now I will be removing it from that file via https://github.com/Shopify/shopify/pull/146422 and adding it directly to the API in this PR.
> Add Access Scope

- lib/shopify_api/resources/order.rb
This is needed to keep the class coding style, improving readability
> Unwrap method body

- lib/shopify_api/resources/asset.rb
- lib/shopify_api/resources/billing_address.rb
- lib/shopify_api/resources/custom_collection.rb
- lib/shopify_api/resources/image.rb
- lib/shopify_api/resources/product.rb
- lib/shopify_api/resources/shipping_line.rb
- lib/shopify_api/resources/shop.rb
This will prevent linters to complain and code editors that has a line wrapping feature enabled to work properly
> Remove trailing whitespaces from lib/

- lib/shopify_api/resources/api_permission.rb
- lib/shopify_api/resources/o_auth.rb
- test/api_permission_test.rb
Fixes https://github.com/Shopify/shopify_api/issues/438.
Adds support for ApiPermission#destroy, which allows applications to remotely uninstall themselves.
~Removes the OAuth class as it's now deprecated.~
> Add support for ApiPermission#destroy

- README.md
- lib/shopify_api/resources/abandoned_checkout.rb
Quick markdown fix to display the links as such on the [Github pages](http://shopify.github.io/shopify_api/).
> Fix README links

- lib/shopify_api/session.rb
- test/session_test.rb
Fixes to use of ActionParams rather than just hash (undefined method map for ActionController::Parameters).
The `encoded_params_for_signature` called map on ActionController::Parameters which was being an issue. I believe that the original PR was the correct one [#352](https://github.com/Shopify/shopify_api/pull/352)
ie. We can also enforce the use of `to_unsafe_hash` on params in `validate_signature` since the method is supposed to only be called with ActionController::Params but I don't know what it would actually mean in terms of retro-compatibility (prior to strong params) other. The safest way to do it is probably this one.
> Rails 5.2.1 session issues fixes

- CHANGELOG
- README.md
- lib/shopify_api/resources/abandoned_checkout.rb
- lib/shopify_api/resources/checkout.rb
- lib/shopify_api/resources/payment.rb
- lib/shopify_api/resources/shipping_rate.rb
- lib/shopify_api/version.rb
- test/abandoned_checkouts_test.rb
- test/checkouts_test.rb
- test/detailed_log_subscriber_test.rb
- test/fixtures/abandoned_checkout.json
- test/fixtures/abandoned_checkouts.json
- test/fixtures/checkout.json
- test/fixtures/checkouts.json
- test/fixtures/payment.json
- test/fixtures/payments.json
- test/fixtures/shipping_rates.json
- test/payment_test.rb
- test/shipping_rate_test.rb
The Abandoned Checkout ActiveResource is mapped to the same RESTful resource as the Checkout ActiveResource.
The current Checkout resource is used to serve two different APIs: Abandoned checkouts API and the actual Checkout API. I would like to have one resource per API:
* `ShopifyAPI::Checkout`: Checkout API (*Admin::CheckoutsController* in core)
* `ShopifyAPI::AbandonedCheckout`: Abandoned Checkouts API (*Admin::AbandonedCheckoutsController* in core)
Note that both APIs are still served on the same URL for the moment, but I plan on creating a new endpoint `admin/abandoned_checkouts` routed the same way.
This should be released as a new version.
It is a breaking change for clients who uses the Abandoned Checkouts API. These clients can either stay on their current version, or update. If …
> Add an abandoned checkout ActiveResource

- CHANGELOG
Adds more detail to the CHANGELOG for release 5.0.0
Also, add a changelog entry for v4.13.0 which was never updated.
> Updated missing entries in CHANGELOG

- lib/shopify_api/resources/smart_collection.rb
- test/fixtures/smart_collection_products.json
- test/smart_collection_test.rb
We're introducing a new feature for merchants, to provide the ability to sort a subset of products at the top of the collection as detailed [here](https://help.shopify.com/en/manual/products/collections/automated-collections/auto-sort). 
In support of these changes, we are making modifications to the SmartCollection API. Specifically, the behaviour of the **order** endpoint will change as detailed in the [updated API docs](https://help.shopify.com/en/api/reference/products/smartcollection). Additionally, we are adding a new products endpoint, to provide the ability to retrieve products in the collection, filtered by manually sorted or automatically sorted.
This PR adds support to the Shopify API gem for the new products endpoint. Since ShopifyAPI already has SmartCollection.products …
> Add support for new products endpoint

- lib/shopify_api/resources/smart_collection.rb
This PR updates `SmartCollection#products` in the following way: 
- If no params are passed then it uses the old endpoint.
- Otherwise, it uses the new one.
Note: This PR is backward compatible since the new endpoint was introduced a week ago and it's still on beta.
> Use new products endpoint only when no params are passed

- lib/shopify_api/resources/tender_transaction.rb
- test/fixtures/tender_transactions.json
- test/tender_transaction_test.rb
**Issue**: https://github.com/Shopify/money-transactions/issues/688
As we prepare to launch the TenderTransaction Api, we need to update our respective Api libraries with the proper resources.
This PR adds a TenderTransaction resource to the gem, as well as a json fixture to test.
> Add new tender transaction resource

- lib/shopify_api/resources/currency.rb
- test/currency_test.rb
- test/fixtures/currencies.json
Adds the new Currency endpoint to the api gem, following similar pattern to what was done for tender transactions being added to the gem.
Docs are here: https://github.com/Shopify/shopify/pull/174966 which are monkey patched currently while this gets updated.
> Added currency endpoint to api gem

- lib/shopify_api/resources/checkout.rb
- test/checkouts_test.rb
- test/detailed_log_subscriber_test.rb
As far as I can tell, all subclasses of `ShopifyAPI::Base` [share the same `headers` object](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/base.rb#L32-L40), unlike `ActiveResource::Base` which [creates a copy in each subclass](https://github.com/rails/activeresource/blob/0ae3010f505b5e6063b7acbcd22cc221995e7873/lib/active_resource/base.rb#L661-L668).
This is intentional, because in ShopifyAPI it's a common pattern to change the access token header to connect to a different shop, and we wouldn't want copies of an access token stored in every subclass.
This means that setting the checkout version header like this ended up setting it for every resource, not just the Checkout resource. Unfortunately, some resources, like the AbandonedCheckout resource, rely on …
> Restrict X-Shopify-Checkout-Version header to ShopifyAPI::Checkout

- lib/active_resource/detailed_log_subscriber.rb
- lib/shopify_api/connection.rb
- shopify_api.gemspec
- test/detailed_log_subscriber_test.rb
- test/test_helper.rb
Warn via the standard `ActiveResource::Base.logger` when ShopifyAPI makes a deprecated API call.
> Log warning when Shopify indicates deprecated API call was performed

- CHANGELOG
- lib/shopify_api/resources/ping/conversation.rb
- lib/shopify_api/resources/ping/delivery_confirmation_details.rb
- lib/shopify_api/version.rb
Updated DeliveryConfirmation resource and Conversation methods to un-nest delivery_confirmation_details hash required for Feedback API endpoint.
> Update DeliveryConfirmation and Conversation Ping resources for Feedback API

- lib/shopify_api/resources/order.rb
- test/order_test.rb
Adds the optional `currency` argument to Order#capture, as per the [API reference](https://help.shopify.com/en/api/reference/orders/transaction).
Apps that are part of the multi-currency beta need to send this parameter to the Transactions API.
cc @kieranmasterton
> Add optional currency parameter to Order#capture

- CHANGELOG
- lib/shopify_api/version.rb
Releasing a new patch version.
```
== Version 5.2.4
* Added `currency` parameter to `ShopifyAPI::Order#capture`. This parameter is required for apps that belong to the
multi-currency beta program.
```
> Packaging for release 5.2.4

- lib/shopify_api/session.rb
- test/session_test.rb
The Shopify API is only available via HTTPS on port 443. I suspect the `protocol` and `port` options in `ShopifyAPI::Session` were added to support local testing, but even our local development environment now uses HTTPS on port 443. I couldn't find any projects that are setting a custom `protocol` or `port` so I think we can safely remove these options.
> Remove support for non-standard protocols and ports.

- README.md
I'm changing the README to assign the session object to `shopify_session` rather than `session`, because `session` is already used in a bunch of microframeworks. 
Copying and pasting code from here can result in a number of hard-to-diagnose headaches if you're accidentally overwriting your existing sessions.
> Change session variable name

- .travis.yml
- Gemfile_ar50
- Gemfile_ar51
- lib/shopify_api/resources/marketing_event.rb
- test/detailed_log_subscriber_test.rb
- test/marketing_event_test.rb
- test/recurring_application_charge_test.rb
- test/test_helper.rb
Updating test suite to support ActiveResource 5.x
Updated our CI run to require passing tests for AR 5.0 and 5.1  anything on master can still fail and not fail the build.
The Countable module correctly handles the difference result structure for custom methods that are in the gem.
The other test failure was only a variation in results in the Shopify threadsafe Active Resource extension.
> Add test support for ActiveResource 5.x 

- lib/shopify_api/limits.rb
- test/limits_test.rb
`http_x_shopify_shop_api_call_limit` is the legacy header so this updates to use the proper one.
edit: this is *not* a breaking change since we respond with both headers. This is better future compatibility.
> Update call limit header

- lib/active_resource/disable_prefix_check.rb
- lib/shopify_api.rb
- lib/shopify_api/disable_prefix_check.rb
- lib/shopify_api/resources/access_scope.rb
- lib/shopify_api/resources/asset.rb
- lib/shopify_api/resources/base.rb
- lib/shopify_api/resources/fulfillment_event.rb
- lib/shopify_api/resources/location.rb
- lib/shopify_api/resources/payment.rb
- lib/shopify_api/resources/ping/conversation.rb
- lib/shopify_api/resources/ping/delivery_confirmation_details.rb
- lib/shopify_api/resources/ping/message.rb
- lib/shopify_api/resources/refund.rb
- lib/shopify_api/resources/shipping_rate.rb
- lib/shopify_api/resources/shop.rb
- lib/shopify_api/resources/smart_collection.rb
- lib/shopify_api/session.rb
- shopify_api.gemspec
- test/base_test.rb
- test/session_test.rb
Bring all the definitions of the `/admin/` rest url prefix into 1 place.
This change is breaking for any Resource that has set a prefix.
`self.prefix = '/admin/orders/:order_id/fulfillments/:fulfillment_id/'`
The change will be to not include `/admin/` at the beginning of the prefix and switch from `prefix=` to `resource_prefix=` .
Example of the change
`self.prefix = '/admin/orders/:order_id/fulfillments/:fulfillment_id/'` 
`self.resource_prefix = "orders/:order_id/fulfillments/:fulfillment_id/"`
> Consolidate slash admin url prefix

- lib/shopify_api/resources/base.rb
Missed 1 use of `prefix=` that should have been migrated to `resource_prefix=` to avoid depreciation warnings.
> Change init_prefix_explicit to use self.resource_prefix.

- RELEASING
I noticed a couple places where the release instructions don't match reality:
* the change log doesn't include dates
* the gem should be published with Shipit
> Correct the release intsructions.

- lib/shopify_api/session.rb
- test/base_test.rb
- test/detailed_log_subscriber_test.rb
- test/session_test.rb
- test/test_helper.rb
Version will now be required when creating a session and using the `temp` method. 
At the same time the session methods have bee updated to use keyword arguments.  4 positional arguments is a bit too hard to remember.
> Remove default for version on session [Breaking change]

- lib/shopify_api/api_version.rb
- lib/shopify_api/session.rb
- test/api_version_test.rb
- test/session_test.rb
Release version type. 
Versions are marked as stable or not stable, Release versions are the only stable versions.
Versions can now be ordered, this allows us to pull the `latest_stable_version` for use in the shopify_app gem config generation.
Helper method for cleanly changing versions.
```
ShopifyAPI::Session.temp(domain: 'shop1.myshopify.com', token: token, api_version: :unstable) do
Shop.current # calls https://shop1.myshopify.com/admin/api/unstable/shop.json
ShopifyAPI::Session.with_version(:no_version) do     
Shop.current # calls https://shop1.myshopify.com/admin/shop.json
end
end
```
> Add release version and helper methods for switching versions

- lib/shopify_api/api_version.rb
- lib/shopify_api/resources/inventory_level.rb
- test/api_version_test.rb
- test/base_test.rb
- test/detailed_log_subscriber_test.rb
- test/session_test.rb
- test/test_helper.rb
Remove the NoVersion.  The NoVersion was an intermediate step and is no longer need to be supported.
> Drop no version.

- lib/shopify_api/resources/base.rb
- test/base_test.rb
https://github.com/Shopify/shopify_api#getting-started
When I set like below, the error occurred.
`ShopifyAPI::Base.api_version = '2019-04'`
```
/shopify_api-7.0.0/lib/shopify_api/resources/base.rb:84:in `prefix': undefined method `construct_api_path' for "2019-04":String (NoMethodError)
```
To Create ApiVersion like Session do.
> fix set base api version

- README.md
Replacement PR for #378. Updates required Ruby version to match [the gemspec](https://github.com/Shopify/shopify_api/blob/master/shopify_api.gemspec#L26).
> Update required Ruby version in README

- lib/shopify_api/resources/base.rb
Since we only support ActiveResource 4.1 and above, we no longer need to check if the `headers` threadsafe attribute exists.
The threadsafe and non-threadsafe version checks were added in https://github.com/Shopify/shopify_api/pull/95, before we could rely on the threadsafe attributes existing.
> Assume threadsafe headers.

- README.md
- lib/active_resource/collection_ext.rb
- lib/shopify_api.rb
- lib/shopify_api/collection_pagination.rb
- lib/shopify_api/pagination_link_headers.rb
- test/pagination_test.rb
Implements a convenient API for using our new [relative cursor pagination](https://help.shopify.com/en/api/guides/paginated-rest-results), which has been partially released as of API version 2019-07.
Rather than providing an automatic way to iterate through all records in the query, we're adding the following methods to any model collection:
- `next_page?`
- `previous_page?`
- `fetch_next_page`
- `fetch_previous_page`
This allows you to perform the navigation however you see fit. Here is an example of using the API to iterate and process a list of all pending orders:
```ruby
orders = ShopifyAPI::Order.find(:all, params: { financial_status: 'pending' })
process_orders(orders)
while orders.next_page?
orders = orders.fetch_next_page
process_orders(orders)
end
```
Currently making all …
> Implements relative cursor pagination.

- README.md
- lib/shopify_api/defined_versions.rb
Adds a 2019-10 API version, which will contain, among other items, full relative cursor pagination from https://github.com/Shopify/shopify_api/pull/594.
> Adds a 2019-10 prerelease API version

- lib/shopify_api/collection_pagination.rb
- test/pagination_test.rb
Changes support for relative cursor pagination to `2019-10`. This feature was added in https://github.com/Shopify/shopify_api/pull/594 under `unstable`, but is now generally available in the `2019-10` pre-release and later versions.
> Change cursor pagination API version to 2019-10

- lib/shopify_api/api_version.rb
- lib/shopify_api/resources/base.rb
- test/api_version_test.rb
- test/base_test.rb
Currently if you try to access a resource without setting an api_version first, you raise an exception:
```
NoMethodError: undefined method `construct_api_path' for nil:NilClass`
from .../shopify_api/lib/shopify_api/resources/base.rb:73:in `prefix'
```
Its not a super clear error. Instead, lets raise an error if the api_version hasn't been set (aka `ShopifyAPI::Base.api_version` would return nil) to let developers know they need to set the api version. This error is super easy to run into if you spin up the shopify_api_console and forget you need to set a version first.
> raise ApiVersionNotSetError if Base.api_version is nil

- CHANGELOG.md
- lib/shopify_api/version.rb
To include https://github.com/Shopify/shopify_api/pull/611
> Packaging for release 7.1.0

- lib/shopify_api/api_version.rb
- lib/shopify_api/resources/base.rb
- lib/shopify_api/session.rb
- test/api_version_test.rb
- test/base_test.rb
- test/session_test.rb
~~1. Not strictly a bug, but Session defaults api_version to nil whereas Base defaults it to ApiVersion::NullVersion. For consistency sake, lets keep them the same.~~
2. Weird edge case, but if you for some reason stored the value of Base.api_version and then find that version stored, you'd create an ApiVersion called NullVersion. Again, maybe not strictly a bug, but I don't think anyone would intentionally try to find NullVersion and intend to create it. The following example seems like a legit stumbling block, so lets smooth the road so to  speak. 
```ruby
ShopifyAPI::ApiVersion.version_lookup_mode
ShopifyAPI::Base.api_version
original_version = ShopifyAPI::Base.api_version
ShopifyAPI::Base.api_version = '2019-07'
ShopifyAPI::Base.api_version = original_version …
```
> ApiVersion::NullVersion tweaks

- lib/shopify_api/session.rb
fixes #620 
This fixes a small consistency issue in code style. As far as the tests are concerned they are all accessing this hash with indifferent access, and I believe at this point the parameters are coming from a controller so it should already have indifferent access.
I tried to look for usage in our ShopifyApp gem but it seems like that part is taken care of by the omniauth gem and does not use this functionality.
> Small consistency change

- lib/shopify_api/paginated_collection.rb
- test/pagination_test.rb
Extract `page_info` from `next_url` and `previous_url` to make cross relative cursor based pagination work across page loads.
Solving issue https://github.com/Shopify/shopify_api/issues/624
> Make relative cursor based pagination work across page loads

- CHANGELOG.md
- lib/shopify_api.rb
- lib/shopify_api/connection.rb
- lib/shopify_api/message_enricher.rb
- test/message_enricher_test.rb
This PR makes 4xx error messages more informative.
Instead of having this:
```
ActiveResource::ResourceInvalid, "Failed.  Response code = 422.  Response message = Unprocessable Entity.
```
the message will contain the error from `response.body['error']`
```
ActiveResource::ResourceInvalid, "Failed.  Response code = 422.  Response message = Unprocessable Entity (Cannot cancel a paid and fulfilled order).
```
so that it would be easier to quickly identify what went wrong
> Enrich 4xx error message with error text from response.body

- test/api_version_test.rb
- test/fixtures/api_versions.json
- test/fixtures/apis.json
- test/meta_test.rb
Release 2020-01 REST Admin API.
> Release 2020-01 REST ADMIN API VERSION

- lib/shopify_api/resources/collection.rb
- test/collection_test.rb
Release the endpoint `Collections#products` in the 2020-01 REST ADMIN API version.
https://help.shopify.com/en/api/reference/products/collection?api[version]=2020-01
Depends on https://github.com/Shopify/shopify_api/pull/656
> Release 2020-01 Collections#products

- CHANGELOG.md
- lib/shopify_api/version.rb
Packaging for release 8.1.0:
- Release 2020-01 Collections#products #657
https://github.com/Shopify/shopify_api/pull/657
- Release 2020-01 REST ADMIN API VERSION https://github.com/Shopify/shopify_api/pull/656
- Enrich 4xx error message with error text from response.body #647 https://github.com/Shopify/shopify_api/pull/647
> Package release for 8.1.0

- lib/shopify_api/resources/assigned_fulfillment_order.rb
- lib/shopify_api/resources/fulfillment_order.rb
- lib/shopify_api/resources/order.rb
- test/assigned_fulfillment_order_test.rb
- test/fixtures/assigned_fulfillment_orders.json
- test/fixtures/fulfillment_order.json
- test/fixtures/fulfillment_orders.json
- test/fixtures/fulfillments.json
- test/fulfillment_order_test.rb
- test/order_test.rb
This PR adds the following read requests:
- GET orders/:order_id/fulfillment_orders
- GET assigned_fulfillment_orders
- GET fulfillment_orders/:fulfillment_order_id
- GET fulfillment_orders/:fulfillment_order_id/fulfillments
Subsequent PRs will add fulfillment order related write requests to relevant resources.
The approach I took was pretty straight forward with the following notable choices:
- the resources returned via `AssignedFulfillmentOrder` are converted to `FulfillmentOrder` type so that subsequent actions defined on FulfillmentOrder may be used
- the `fulfillments` method on FulfillmentOrder will get the related fulfillments
> Add fulfillment order related read requests

- lib/shopify_api/resources/fulfillment_order.rb
- test/fulfillment_order_test.rb
- test/test_helper.rb
This PR adds the following POST requests:
POST fulfillment_orders/:fulfillment_order_id/move
POST fulfillment_orders/:fulfillment_order_id/cancel
POST fulfillment_orders/:fulfillment_order_id/close
GET requests are in PR #633
Subsequent PRs will add other fulfillment order related write requests to relevant resources.
The approach I took was to add the `move`, `cancel`, and `close` actions on the `FulfillmentOrder` resource.
Because there's already a legacy `Fulfillment` resource, I named the fulfillment orders fulfillment as `FulfillmentOrderFulfillment`.
Since all that's really needed is the `fulfillment_order_id`, if it's known you can do (rather than querying it first):
```
closed_fulfillment_order = FulfillmentOrder.new(id: <the-fo-id>).close
```
> Add move, cancel, close actions FulfillmentOrder

- lib/shopify_api/resources/fulfillment_order.rb
- test/fulfillment_order_test.rb
This PR adds the following POST requests:
POST fulfillment_orders/:fulfillment_order_id/fulfillment_request
POST fulfillment_orders/:fulfillment_order_id/fulfillment_request/accept
POST fulfillment_orders/:fulfillment_order_id/fulfillment_request/reject
POST fulfillment_orders/:fulfillment_order_id/cancellation_request
POST fulfillment_orders/:fulfillment_order_id/cancellation_request/accept
POST fulfillment_orders/:fulfillment_order_id/cancellation_request/reject
GET requests are in PR #633
Actions move, cancel, close for fulfillment orders are in PR #635
Subsequent PRs will add other fulfillment order related POST requests to relevant resources.
Since all that's really needed is the `fulfillment_order_id`, if it's known you can do (rather than querying it first):
``` …
```
> Fulfillment orders fulfillment cancellation request

- lib/shopify_api/resources/fulfillment.rb
- lib/shopify_api/resources/fulfillment_v2.rb
- test/fulfillment_test.rb
- test/fulfillment_v2_test.rb
This PR adds the following POST requests:
POST fulfillments (via FulfillmentOrderFulfillment.save)
POST fulfillments/:fulfillment_id/update_tracking
POST fulfillments/:fulfillment_id/cancel
GET requests are in PR #633
FulfillmentOrder actions move, cancel, close are in PR #635
FulfillmentOrder actions fulfillment_request (+ accept/reject), cancellation_request (+ accept/reject) are in PR #637
Subsequent PRs will add other fulfillment order related requests to relevant resources.
Since all that's really needed is the `fulfillment_id`, if it's known you can do (rather than querying it first):
```
FulfillmentOrderFulfillment.new(id: <the-fulfillment-id>).update_tracking(<params>)
```
Notes to reviewer:
- there's already a `Fulfillment` resource which I haven't yet determined is the …
> Add save, update_tracking, and cancel actions to FulfillmentOrderFulfillment resource

- README.md
Add a bit more explanation to cursor based pagination docs so that people are not confused like in issue [624](https://github.com/Shopify/shopify_api/issues/624)
> improve documentation for cursor based pagination

- README.md
- lib/shopify_api/session.rb
- test/session_test.rb
Fixes https://github.com/Shopify/shopify_api/issues/466
A re-attempt at the solution first investigated in https://github.com/Shopify/shopify_api/pull/467
- Makes a **breaking change** in requiring `redirect_uri` to `create_permissions_url`, since this is actually required today
- Adds an options hash so that we don't break the interface again, which for now supports passing `state`
- Updates readme
cc @jamiemtdwyer @richter-alex let me know your thoughts
> Added options hash to create_permission_url and makes redirect_uri required

- lib/shopify_api/resources/fulfillment_order.rb
- lib/shopify_api/resources/fulfillment_order_locations_for_move.rb
- test/fixtures/fulfillment_order_locations_for_move.json
- test/fulfillment_order_test.rb
Closes: https://github.com/Shopify/shopify/issues/211513
This PR is to implement the API for REST API:
_GET fulfillment_orders/:fulfillment_order_id/locations_for_move_
> Add locations_for_move API

- lib/shopify_api/resources/assigned_fulfillment_order.rb
- lib/shopify_api/resources/base.rb
- lib/shopify_api/resources/fulfillment_order.rb
- lib/shopify_api/resources/fulfillment_v2.rb
- lib/shopify_api/resources/order.rb
- test/assigned_fulfillment_order_test.rb
- test/base_test.rb
- test/fulfillment_order_test.rb
- test/fulfillment_order_test_helper.rb
- test/fulfillment_test.rb
- test/fulfillment_v2_test.rb
- test/order_test.rb
Closes: https://github.com/Shopify/shopify/issues/230988
Added version check for all Fulfillment Order related APIs. `NotImplementedError` is returned if the `api_version` is older than `2020-01`. 
Tests are updated to activate the session with different versions (i.e., `2020-01` or `2019-10`).
The PR is bit big, but most changes are in `fake`. For example:
Before
```ruby
fake 'assigned_fulfillment_orders.json?assigned_status=cancellation_requested', 
method: :get,
body: fulfillment_order_fixture, 
extension: false
```
After
```ruby
fake 'assigned_fulfillment_orders',
url: "#{@url_prefix}/assigned_fulfillment_orders.json?assigned_status=cancellation_requested",
method: :get,
body: fulfillment_order_fixture,
extension: false
```
Also, append `?w=1` in url would make it a bit easy to …
> Add versioning for Fulfillment Platform APIs

- CHANGELOG.md
- lib/shopify_api/version.rb
Closes: https://github.com/Shopify/shopify/issues/230990
Bump the release version to `8.2.0` and update the change log.
> Packaging for release 9.0.0

- CHANGELOG.md
- lib/shopify_api/message_enricher.rb
- test/message_enricher_test.rb
According to the [documentation](https://help.shopify.com/en/api/getting-started/response-status-codes), there might be `errors` key containing an array of error messages. In this PR we check if the response body has `errors` key if we didn't found `error`
> Take into account semantical 'errors' key in JSON body for 422 responses

- lib/active_resource/detailed_log_subscriber.rb
- test/detailed_log_subscriber_test.rb
Closes https://github.com/Shopify/shopify/issues/233879
TL;DR  This pull request is raised to add a warning message case of API Version being used to make a call is expired or will expire within 30 days
**Background:**
Currently, a warning header is added to the responses of all admin and storefront APIs that are using a version that expires within 30 days or is expired already. This was done through https://github.com/Shopify/shopify/pull/232580
Now, we want to raise warning messages through the Shopify API gem as well if API calls are made using expired or EOL versions. 
**Solution**
The response headers of the API responses are checked for the presence of the version EOL warning header. If present, a warning message is raised.
> warning raised for version eol

- CHANGELOG.md
I noticed that `CHANGELOG.md` didn't have the correct markdown syntax, so I switched from rdoc (I think) to markdown.
I followed rubocop's nice syntax: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md
You can see the diff here (it's really just the version headings):
https://github.com/Shopify/shopify_api/pull/687/files?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
And here you can see the full preview:
https://github.com/Shopify/shopify_api/blob/8bf000ef44f8783d4dc2b4c89ce3835de1fe35f6/CHANGELOG.md
> Conform to Markdown syntax

- CHANGELOG.md
- lib/shopify_api/version.rb
We had rolled out a warning header to all admin and storefront APIs (REST and Graphql) if an unsupported or soon to be unsupported version pf the API was used in Shopify Core. 
Shopify/shopify#232580
Now we have added a warning message within the Shopify API gem as well.
https://github.com/Shopify/shopify_api/pull/685
This version bump is done to release the changes in shopify api gem
> Packaging for release 9.0.1

- docs/graphql.md
Adding instructions for using the SHOP_DOMAIN and ACCESS_TOKEN arguments instead of SHOP_URL when running the schema dump rake task. This helps with understanding the needed arguments, when using this gem for public apps.
> Clarify shopify_api:graphql:dump rake task

- lib/shopify_api/graphql.rb
- test/graphql_test.rb
ApolloClient is generating, in the same directory as my schemas, a `shopify-schema-unions-and-interfaces.json` file. This makes `initialize_clients` raise an exception when it encounters it.
Unfortunately, ApolloClient does not allow to disable the creation of that file, or to give it a different name.
After talking to @swalkinshaw on Slack, we decided that putting an option to not raise on `initialize_clients` was the best approach for now.
> Add option to not raise if non-matching schema name

- lib/shopify_api/resources/discount_code_batch.rb
- test/discount_code_batch_test.rb
- test/fixtures/discount_code_batch.json
- test/fixtures/discount_code_batch_discount_codes.json
Support the API batch endpoints.
https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#batch_create-2020-01
https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#batch_show-2020-01
https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#batch_discount_codes_index-2020-01
Tests shows some usage examples for the 3 endpoints.
> Add support for Discount Code batch endpoints

- lib/shopify_api/resources/product.rb
- lib/shopify_api/resources/variant.rb
- test/product_test.rb
- test/test_helper.rb
- test/variant_test.rb
fixes #632
The following fields on Product (`total_inventory`) and Variant (`inventory_quantity_adjustment`, `inventory_quantity`, `old_inventory_quantity`) were deprecated earlier this year and were removed in the 2019-10 api version.
This PR updates the code and adds tests to ensure the behaviour is correct. 
Reviewer's note: In `test/test_helper.rb` I changed the code to return the current API version if none was specified. The old code returned the Jan 2019 version. I believe this new behaviour is correct but would like confirmation.
> Add validation and tests for deprecation of product and variant inventory-related fields

- shopify_api.gemspec
- test/test_helper.rb
Prevents this warning when running the tests:
Mocha deprecation warning at ... test/test_helper.rb:5:in `require':
Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
Requiring `mocha/setup` was deprecated in 1.10.0:
https://github.com/freerange/mocha/blob/master/RELEASE.md#1100
> Fix `mocha/setup` deprecation warning

- lib/shopify_api/session.rb
- test/session_test.rb
It's convenient to be able to compare `Session` objects (when testing, for example).
Co-authored with @gbossh 
For: https://github.com/Shopify/shopify_app/pull/951
> Implement Session#==

- .travis.yml
Ruby 2.7 [was released](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/) on 25 Dec 2019 and the latest version is 2.7.1
> Test against Ruby 2.7

- lib/shopify_api/resources/base.rb
- test/base_test.rb
resolves #640 
Removes resetting the api_version when clearing the session. In the `test\base_test.rb` there is no logic the shows the session clearing should also clear the api_version.
@tanema
> Update clear_session not to clear the api-version

- lib/shopify_api/resources/smart_collection.rb
- test/smart_collection_test.rb
The `SmartCollection#products` endpoint was behind a beta flag, which was never enabled. Sitting at 0% since 2018. The REST API documentation was never added. All calls to this endpoint would result in a 401. Since we're removing the endpoint from the controller, I'm first removing it from the API.
I checked with #api-patterns and they confirmed this is safe to remove.
> removed unused smartcollection.products endpoint

- CHANGELOG.md
- lib/shopify_api/pagination_link_headers.rb
- lib/shopify_api/version.rb
Fixes #713 
Currently, when using REST based collection pagination, the request made using `.fetch_next_page` and `fetch_previous_page` actually includes the base site twice.
Normal request is fine:
```
prods = ShopifyAPI::Product.find(:all, params: {limit: 5})
GET https://myshop.myshopify.com:443/admin/api/2020-01/products.json?limit=5
```
but then fetching next or previous page results in the following request:
```
=> GET https://myshop.myshopify.com:443https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=5&page_info=eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6MjA3MDE5MjE2MDgzMywibGFzdF92YWx1ZSI6IlByaW1lIHRpbWUifQ
```
Strangely, Shopify works when calling the api like that most of the time.. but sometimes it randomly fails with a "522 - Bad Gateway" error.
This happens because …
> Make cursor based pagination return relative uri's when fetching next and previous pages

- lib/shopify_api/resources/product.rb
- lib/shopify_api/resources/variant.rb
- test/product_test.rb
- test/variant_test.rb
This is a duplicate of https://github.com/Shopify/shopify_api/pull/655 but with the issue fixed, I posted the fix on that thread but no one paid attention for so long.
> Inventory param patch fix

- docs/_config.yml
- docs/_includes/footer.html
- docs/_includes/head.html
- docs/_layouts/index.html
- docs/index.md
Using a `gh-pages` branch appears to be discouraged/deprecated for new GitHub projects, and is awkward since it's not obvious where the content lives. This leads to stale documentation.
This PR copies the current content from the `gh-pages` branch. It's outdated, but we can address that afterwards.
After this PR is merged we'll need to:
Note that the `/docs` directory already exists and contains a `graphql.md` page.
> Eliminate gh-pages branch

- .gitignore
- Gemfile
This will allow local preview of `docs/` with:
```
bundle install --with=docs
bundle exec jekyll serve --source docs
```
> Add Jekyll to Gemfile as optional

- docs/index.md
The current page at https://shopify.github.io/shopify_api/ is quite outdated. This PR simply copies the currrent README from master.
Longer-term I think we need a better way to manage this. I'll open a separate issue to discuss.
~~Unfortunately there is no way to fully preview how this will exactly look on shopify.github.io so some further tweaks may be required.~~ In particular, the heading levels (e.g. `### Ruby version`) have changed.
(supercedes #734)
<details>
<summary>Click to see a very tall screenshot</summary>
> Update Open Source docs page from master README

- docs/graphql.md
- lib/shopify_api/graphql.rb
- test/graphql_test.rb
First I want to thank you all for implementing a more memory efficient GraphQL client. We are really excited to delete ours. I also really appreciate the light wrapper approach.
Throughout our application we use the graphql api and one of the first things we noticed was that we needed to check the result object returned from the graphql client to determine if an error occurred. This wasn't something we liked scattered throughout our code and as a result we enhanced the client to parse errors and raise exceptions instead.
However, we appreciate this may not be the approach everyone wants to take. We also really like the lightweight approach. It better enables developers to instrument heuristics they prefer.
In order to maintain flexibility, respect the light wrapper approach, and enable …
> Allow for executing client to be set dynamically

- lib/shopify_api/session.rb
- test/session_test.rb
Paired with @carmelal for this one, to fix #743. We changed the way sessions (and temp sessions) are created so that they default to `Base.api_version` if no `api_version` is given, so that developers don't need to pass in the version every time they need a session.
> Default sessions to Base api_version

- CHANGELOG.md
- bin/shopify
- lib/shopify_api/version.rb
- shopify_api.gemspec
With the upcoming CLI v2 changes, a new `shopify` executable will be generated and distributed, which will overwrite the current binary from this repo.
This is what happens when the current binary is executed:
```
% shopify
shopify command is no longer bundled with shopify_api.
if you need these tools, install the shopify_cli gem
```
Therefore, what this change does is simply fully remove the binary which no longer belongs to this gem so it doesn't accidentally overwrite the new CLI binary.
The version was bumped (patch bump since no function actually changed) so future installs don't bring the binary in over the new one.
> Remove old shopify binary from API

- lib/shopify_api/resources/base.rb
It's deprecated since https://github.com/rails/rails/pull/39733, but very easy to replace.
> Stop using the deprecated URI.parser

- lib/shopify_api/session.rb
- test/session_test.rb
Fixes #744.
If an app was set up using `ShopifyAPI::Base.user/password`, temp sessions wouldn't work properly because those values would be set for them as well, which might not be desirable.
This change essentially ensures that we clear those values on `ShopifyAPI::Base` before running the block and restore them before exiting. That way, the temp session is indeed fresh.
**Concern**: while starting a fully fresh session makes sense and the suggested fix works, I wonder if it can be considered backward compatible. There could be a scenario where someone relies on the Basic auth settings being used for temp sessions, and those apps would be broken if they bumped their API version.
> Clean up Base user / password on temp sessions

- docs/graphql.md
This simply fixes a typo in the GraphQL documentation.
> Fix a typo in the GraphQL Docs

- lib/shopify_api/resources/product.rb
- lib/shopify_api/resources/variant.rb
- test/product_test.rb
- test/variant_test.rb
Fixes #775 
We had reports that the changes made in #731 were causing the JSON serialization of API objects to break when `Base.api_version` wasn't set, for instance outside the scope of a temp session.
The issue here was that we were filtering the fields out only when serializing the Product / Variant objects, rather than removing them altogether (even though they were no longer allowed in the API after version `2019-10`).
This PR changes those objects so that we remove the fields when the object is first created, so that we don't need to check later on.
> Filter unwanted product / variant attributes on creation

- .github/workflows/build.yml
These may be useful in dev but in CI they're noisy.
Example:
```
Post-install message from i18n:
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.
If you are upgrading your Rails application from an older version of Rails:
Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
If you are starting a NEW Rails application, you can ignore this notice.
For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
```
> Hide bundler post-install messages

- lib/shopify_api/session.rb
- test/session_test.rb
In #817 we ran into an issue relating to ActiveSupport not being loaded when updating to Rails 6.1.0. We only use it for some trivial time-related helpers – I think we can drop it completely.
> Avoid depending on ActiveSupport

- CHANGELOG.md
I realised we still have a bunch of other places that depend on ActiveSupport.
> Clarify CHANGELOG entry for ActiveSupport

- README.md
We use `#{SHOP_NAME}` in some places but `SHOP_NAME` in others. Let's make this consistent so that it's easy to copy and paste example code when experimenting.
> Use consistent `SHOP_NAME` constant in code examples

- .github/ISSUE_TEMPLATE.md
- CHANGELOG.md
- README.md
- lib/active_resource/detailed_log_subscriber.rb
- lib/shopify_api.rb
Logging is enabled through `export SHOPIFY_LOG_PATH={path}`
Is this the right way to go about logging? Current solution is to have users set an env variable SHOPIFY_LOG_PATH.
Should I also include some method inside the API to enable logging such as `ShopifyAPI::Logging=true`?
> Add logging based on env var

- CHANGELOG.md
- lib/shopify_api/resources/fulfillment_order.rb
- test/fixtures/assigned_fulfillment_orders.json
- test/fixtures/fulfillment_order.json
- test/fixtures/fulfillment_orders.json
- test/fulfillment_order_test.rb
Fixes: https://github.com/Shopify/shopify/issues/255067
Add `open` and `reschedule` APIs support for `scheduled` fulfillment orders.
> Add API support for scheduled fulfillment orders

- CHANGELOG.md
- lib/shopify_api/version.rb
* Provide `ApiAccess` value object to encapsulate scope operations [#829](https://github.com/Shopify/shopify_api/pull/829)
> Packaging for release 9.3.0

- lib/shopify_api/session.rb
- test/session_test.rb
> Related: https://github.com/Shopify/shopify_app/pull/1192
This PR introduces an `access_scopes` attribute to the Session object. 
1. Do we determine the validity of a session through this attribute?
2. Is there immediate benefit in returning a `ShopifyAPI::ApiAccess` object? Will a string suffice?
3. ~~Is this level of error handling needed?~~
> Add access_scopes attribute to session object

- CHANGELOG.md
- Gemfile.lock
- lib/shopify_api/version.rb
* [#843](https://github.com/Shopify/shopify_api/pull/843) Introduce a new `access_scopes` attribute on the Session class.
* Specifying this in the Session constructor is optional. By default, this attribute returns `nil`.
> Packaging for release 9.4.0

- lib/active_resource/detailed_log_subscriber.rb
- test/detailed_log_subscriber_test.rb
Removing sensitive information from the log
`INFO -- : Headers: {"Accept"=>"application/json", "User-Agent"=>"ShopifyAPI/9.3.0 ActiveResource/5.1.1 Ruby/2.7.1", "X-Shopify-Access-Token"=>"..."}`
becomes
`INFO -- : Headers: {"Accept"=>"application/json", "User-Agent"=>"ShopifyAPI/9.3.0 ActiveResource/5.1.1 Ruby/2.7.1"}`
> Remove access tokens in log headers

- README.md
- lib/shopify_api/session.rb
- test/session_test.rb
`create_permission_url` should be able to take in a `grant_options` parameter.
> Update method to use grant_options

- Gemfile.lock
- lib/shopify_api/hmac_params.rb
- shopify_api.gemspec
It made sense to use these utils when they were part of the stdlib but now it's a bit silly to pull a whole webserver for 5 lines of code.
> Drop the dependency on webrick

- lib/shopify_api/context.rb
When testing, we sometimes produced a log line when trying to load `unstable` REST resources, which don't exist. This PR changes the loading code so we don't even try for unstable, since those will never be there.
> Don't log missing resource folder for unstable

- CHANGELOG.md
- lib/shopify_api/rest/base.rb
- test/clients/base_rest_resource_test.rb
Sometimes, the API will send back data that's not exactly as documented, such as the `optionX` fields in products / variants - those are documented as `option`, but they dynamically accept any number of options.
The current code only accepts fields that are in the "expected" set when loading API data, but in cases like the above, we should just take whatever the API is sending our way.
Via a new unit test.
> Load unknown REST resource attributes from data

- CHANGELOG.md
- Rakefile
- lib/shopify_api/auth/jwt_payload.rb
- test/auth/jwt_payload_test.rb
Contributes to https://github.com/Shopify/first-party-library-planning/issues/203
This PR fixes JWT validation for services running under the `.spin.dev` domain, namely our first party apps.
I have manually hotfixed a spin deployment with this change and validated that the JWT check works as expected. I've also added a unit test to cover this case for future regressions.
> Validating .spin.dev domains in JWT check

- CHANGELOG.md
- lib/shopify_api/auth/jwt_payload.rb
- test/auth/jwt_payload_test.rb
The `validate_shop` from the JWT class is not really necessary, because this information is coming from Shopify, and it is signed, so we can trust that, if the data itself is valid, the shop name will be correct.
Via tests.
> Deprecate unnecessary validate_shop call from JWT class

- CHANGELOG.md
- lib/shopify_api/rest/base.rb
- test/clients/base_rest_resource_test.rb
Fixes issue #930
Adds parameter to `to_hash` so that default behaviour includes readonly attributes; setting the parameter to `true` indicates that `to_hash` is being used to serialize the object for saving (and thus excludes readonly attributes).
Added tests to verify that readonly attributes are included when using the default `to_hash` and excluded when using `to_hash(true)` (i.e, `saving = true`).
> Fixes `to_hash` to include readonly attributes

- CHANGELOG.md
- lib/shopify_api/admin_versions.rb
We didn't update the latest supported version to 2022-04 when it was released, this PR fixes that.
> Update latest API version to 2022-04

- RELEASING.md
It seems best to update these together, otherwise a constraint can prevent the latest version from being used.
> Add note about updating Sorbet

- CHANGELOG.md
- lib/shopify_api/webhooks/request.rb
- test/webhooks/request_test.rb
Webhooks fail when there is a header with a symbol as a key:
```
ShopifyAPITest::Webhooks::WebhookRequestTest#test_with_symbol_headers:
NoMethodError: undefined method `sub' for :clearance:Symbol
Did you mean?  stub
```
This happens e.g. when using Clearance, which adds `:clearance` as a header, containing the Clearance session. This means that webhooks will always fail as soon as you include Clearance into the project. Its middleware always adds that header, even if there is no authenticated request.
Test case within this PR.
> Fix webhook requests for headers with a symbol key

- CHANGELOG.md
- lib/shopify_api/utils/hmac_validator.rb
- test/utils/hmac_validator_test.rb
- test/utils/session_utils_test.rb
Fixes #990
Similar to #952 978, this library needs the ability to verify the `hmac` signature of the query string in the OAuth 2.0 callback using both ew and old API secrets in order to support [API key rotation](https://shopify.dev/apps/auth/oauth/rotate-revoke-api-credentials).
Added new test cases to validate the signature signed with the old secret.
> Validate HMAC using both old and new API secrets

- CHANGELOG.md
- README.md
- docs/usage/graphql.md
As part of the Shopify API and app template strategy, the public repos were renamed to provide a more consistent naming convention.
Where applicable, this PR renames the following repos to match the new naming convention.
- `Shopify/shopify_api` -> `Shopify/shopify-api-ruby`
- `Shopify/shopify-node-api` -> `Shopify/shopify-api-node`
- `Shopify/shopify-php-api` -> `Shopify/shopify-api-php`
- `Shopify/shopify-app-node` -> `Shopify/shopify-app-template-node`
- `Shopify/shopify-app-php` -> `Shopify/shopify-app-template-php`
> Update API repo links (post Editions 2022 tidy-up)

- CHANGELOG.md
- lib/shopify_api/auth/jwt_payload.rb
We currently have a 5s grace period for validating JWTs from session token, but there are cases where that is not long enough and we still end up failing to validate the token.
Increase the period to 10s which seems to eliminate the problem for good.
> Increase session token JWT leeway

- CHANGELOG.md
- lib/shopify_api/auth/oauth.rb
- test/auth/oauth_test.rb
First party apps such as https://shopify-graphiql-app.shopifycloud.com have scopes which are set during installation, rather than being preconfigured.
There is a corresponding update to `shopify_app`: https://github.com/Shopify/shopify_app/pull/1540
Tested as part of the upgrade of https://shopify-graphiql-app.shopifycloud.com
> Allow custom scopes during the auth process

- docs/usage/session_storage.md
session storage document is wrong
`ShopifyAPI::Auth::SessionStore` is not exist.
no change codebase
> Fix typo in session_storage.md

- README.md
Since there are still a number of dependencies in the gemspec, this seemed a little misleading.
> Clarify statement about packages

- README.md
- docs/getting_started.md
- docs/usage/oauth.md
As per https://help.shopify.com/en/manual/apps/private-apps
> Private apps are deprecated and can't be created as of January 2022. Ask your app developer to create a [custom app](https://help.shopify.com/en/manual/apps/app-types#custom-apps). Like private apps, custom apps are built exclusively for your shop, but they don't require open API access to your store or access to your Shopify admin.
> Remove mentions of private apps

- .github/workflows/build.yml
Currently, we're removing the lock file in CI, which causes things to break if there is dependency drift. We should probably delete the lock file every now and then to update things, but it shouldn't be a CI step.
> Don't remove gem lock file in CI

- .github/workflows/stale.yml
At first I thought this action wasn't running because I found so many old issues/prs. The `feature request` label was keeping a lot of issues open that should be marked as stale so I've removed that exclusion rule. 
It looks like there have been a few releases for [this GitHub Action](https://github.com/actions/stale) which I've updated here. 
> Fix stale bot to help clean up super old issues/prs

- CHANGELOG.md
- Gemfile.lock
- lib/shopify_api/version.rb
Shipping `v12.5.0`!
🎩 - I created a new app with the shopify CLI and pointed to this branch and ran `bundle install`. Verified the branch version of the gem was being used. Was able to install my test app on a store and make an API call.
> Packaging for release 12.5.0

- CHANGELOG.md
- lib/shopify_api/clients/http_client.rb
- test/clients/http_client_test.rb
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1033
As indicated in #1033, our error messages have not been structured in a JSON serializable manner making them very difficult to parse and pass off to the front end to handle. 
- Unit tests with the expected error data structure
- Pointed at this local branch with a sample CLI created app and verified the errors were JSON parsable:
```
irb(main):007:0> JSON.parse  "{\"errors\":{\"line_items\":[\"must have at least one line item\"]},\"error_reference\":\"If you report this error, please include this id: 6aa2cdec-9c4f-4f09-8c6d-c059564eacce.\"}"
=> {"errors"=>{"line_items"=>["must have at least one line item"]}, "error_reference"=>"If you report this error, please include this id: …
```
> JSON parseable error messages

- lib/shopify_api/rest/base.rb
`DiscountCode` has an `errors` property that overrides the same property in `base.rb`, creating a Sorbet type conflict. This commit adds the additional typing to allow the override.
Re-running the rest wrapper tests.
- not applicable ~I have added a changelog line.~
> Add extra type to errors for override

- CHANGELOG.md
- lib/shopify_api/webhooks/registry.rb
- test/webhooks/registry_test.rb
- test/webhooks/webhook_registration_queries.rb
Allows more variety of webhook topic names.
Event topic names will allow period as a separator and these need to be translated to GraphQL valid ENUM values.
Checking that the transformation allows strings with period separators.
> Add support for Event topic names

- CHANGELOG.md
- lib/shopify_api/rest/base.rb
- test/clients/base_rest_resource_test.rb
Follow up on the changes in this PR #1149. When a resource has read-only attributes and you attempt to call `save`, the update payload would contain an erroneous entry for the read-only attributes with the value of `HashDiff::NO_VALUE`.  
The root cause of this issue is that the `original_state` contains the read-only attributes, however the lookup of the current resource state with `to_hash(true)` strips them out. Performing a `left_diff` hash comparison then yields the resulting `HashDiff::NO_VALUE`. 
The fix I've implemented is to use a copy of the `original_state` hash with read-only attributes removed when performing the comparison to see which attributes to update.
I've written a new unit test for the base resource and verified it failed as expected prior to implementing the fix.
> Ignore read-only attributes when updating through REST resources

- CHANGELOG.md
- Gemfile.lock
- lib/shopify_api/context.rb
- shopify_api.gemspec
Fixes #1058
- Removes the pinning of zeitwerk to version 2.6.5
`bundle exec rake test:rest_wrappers` now runs with zeitwerk 2.6.5+
> Unpin zeitwerk version from 2.6.5

- CHANGELOG.md
- lib/shopify_api/rest/base.rb
- lib/shopify_api/rest/resources/2022_10/assigned_fulfillment_order.rb
- lib/shopify_api/rest/resources/2022_10/customer_address.rb
- lib/shopify_api/rest/resources/2022_10/fulfillment_request.rb
- lib/shopify_api/rest/resources/2022_10/order_risk.rb
- lib/shopify_api/rest/resources/2023_01/assigned_fulfillment_order.rb
- lib/shopify_api/rest/resources/2023_01/customer_address.rb
- lib/shopify_api/rest/resources/2023_01/fulfillment_request.rb
- lib/shopify_api/rest/resources/2023_01/order_risk.rb
- lib/shopify_api/rest/resources/2023_04/assigned_fulfillment_order.rb
- lib/shopify_api/rest/resources/2023_04/customer_address.rb
- lib/shopify_api/rest/resources/2023_04/fulfillment_request.rb
- lib/shopify_api/rest/resources/2023_04/order_risk.rb
- lib/shopify_api/rest/resources/2023_07/assigned_fulfillment_order.rb
- lib/shopify_api/rest/resources/2023_07/customer_address.rb
- lib/shopify_api/rest/resources/2023_07/fulfillment_request.rb
- lib/shopify_api/rest/resources/2023_07/order_risk.rb
- test/clients/base_rest_resource_test.rb
- test/rest/2022_10/customer_address_test.rb
- test/rest/2023_01/customer_address_test.rb
- test/rest/2023_04/customer_address_test.rb
- test/rest/2023_07/customer_address_test.rb
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1018
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1190
Allowing multiple response body names to be passed in so we can check and build a response based on what key matches the for the class
Created a fresh app and pre-populated test store and made sure we can create a fulfillment request without sorbet error
Get a response back from CustomerAddress.all
> Convert json_response_body_names to array

- BREAKING_CHANGES_FOR_V10.md
- README.md
Add more examples and reference for upgrading this gem from v9.
[New dedicated page - "Breaking change notice for version 10.0.0"](https://github.com/Shopify/shopify-api-ruby/blob/421e1823fcda3d4cd34b966ddc96683795ebd2e1/BREAKING_CHANGES_FOR_V10.md#breaking-change-notice-for-version-1000)
[Link from README](https://github.com/Shopify/shopify-api-ruby/blob/421e1823fcda3d4cd34b966ddc96683795ebd2e1/README.md#breaking-change-notice-for-version-1000)
[Existing docs on v10 upgrade](https://github.com/Shopify/shopify-api-ruby/blob/712c960d453aeb14e5422c7e80413917bb62a8bb/README.md#breaking-change-notice-for-version-1000)
> Improve V9->v10 Upgrade Docs

- BREAKING_CHANGES_FOR_V10.md
Add some docs explaining resource connection
> Add section on resource connections

- lib/shopify_api/context.rb
In [this commit](https://github.com/rails/rails/commit/1fbd812c47f7ba840390942e56d9b2ebbc260901) which is part of Rails 7.1, the default logger changed from `Logger` to the new `BroadcastLogger`.
This change causes a `sorbet-runtime` error because `BroadcastLogger` does not inherit from `Logger` and therefore doesn't match the expected type in the signature for the `setup` method.
This ends up being a weird issue. The `BroadcastLogger` class was designed to match the same interface as `Logger`. However, we can't use a Sorbet interface in this case. For an interface to work, it needs to be included in the actual runtime - and Rails won't include a Sorbet construct in the codebase.
Even using `T.any(Logger, Rails::BroadcastLogger)` wouldn't work properly. This gem has a dependency on Active …
> Make logger untyped

- .github/workflows/build.yml
Looking at the pipeline failures we've been seeing for PRs, the consistent theme was HMAC validation tests failing due to OpenSSL. After installing OpenSSL as part of the setup process, I ran the pipelines twice and saw two successful runs.
> Add OpenSSL install to the GH pipelines

- Gemfile.lock
- shopify_api.gemspec
When I was working on #1226, I noticed that this gem still has the `ruby-lsp` as a development dependency.
We made changes so that the server can auto-update itself and it's no longer recommended to leave it in the gemspec or Gemfile.
This PR just removes the `ruby-lsp` from the gemspec so that people working on it get auto-updates. I also upgraded the `parser` gem because there's a bug that prevents the LSP from starting in older versions.
These are only development changes.
Opened VS Code on the project, verified that I got the latest Ruby LSP server version running.
> Remove `ruby-lsp` from dependencies

- CHANGELOG.md
- lib/shopify_api/clients/http_client.rb
- lib/shopify_api/context.rb
- test/clients/http_client_test.rb
- test/context_test.rb
RE: https://github.com/Shopify/shopify-api-ruby/issues/1235
This PR adds new `api_host` "setting" to `Context`. The `HttpClient` will use `api_host` when set, otherwise default to calling the API as specified by the `session.shop` value.
Whilst this feels a little weird to add this value to `Context`, it seems to be way the `ShopifyAPI` gem is "configurable" by consumers.
Unit tests in this project and using this branch in a service.
> Add api_host to ShopifyAPI::Context

- CHANGELOG.md
- lib/shopify_api/auth/session.rb
- test/auth/session_test.rb
There isn't currently a method available to check if an auth session is expired (for online tokens mainly). It's up to each app to implement the method if they want to do such check. This PR adds an `expired?` method to the `Session` that will check the `expires` attribute if it exists.
We are planning to add a check on the expiry date in `shopify_app` to trigger an early re-auth, and having that method will make the check cleaner
A new method can be used to check if the session is expired. No impact as long as it's not used
Unit tests provided in the PR
> Add expired? method to check if session is expired

- .rubocop.yml
- CHANGELOG.md
- lib/shopify_api/clients/graphql/client.rb
- lib/shopify_api/clients/http_client.rb
- lib/shopify_api/clients/http_response.rb
- lib/shopify_api/context.rb
- test/clients/http_client_test.rb
- test/clients/http_response_test.rb
- test/test_helper.rb
https://github.com/Shopify/shopify-api-ruby/assets/23265671/144cffa0-aa34-4a5b-a51a-38c07299b5cd
Fixes #1210
Starting in the version 10 upgrade graphql response were no longer available to be access with dot notation. 
This PR adds a context option(`response_as_struct`) that will return the  graphql API responses as a struct, so that they will be accessible via either dot or hash notation.
```ruby
created_product = response.body["data"]["productCreate"]["product"]
created_product2 = response.body.data.productCreate.product
```
* This gem was used locally to test GraphQL, REST, rest resources and install flow
> Add dot notation accessing for graphql responses

- docs/usage/graphql.md
* Adds documentation for the [response as struct context option](https://github.com/Shopify/shopify-api-ruby/pull/1246).
> Add documentation covering the response as struct context option

- CHANGELOG.md
- lib/shopify_api/auth/oauth.rb
- lib/shopify_api/auth/oauth/access_token_response.rb
- lib/shopify_api/auth/session.rb
- lib/shopify_api/auth/token_exchange.rb
- test/auth/oauth/access_token_response_test.rb
- test/auth/session_test.rb
- test/auth/token_exchange_test.rb
This introduces the token exchange API to fetch access tokens based on the [Token Exchange spec](https://datatracker.ietf.org/doc/html/rfc8693)
This has been already added in `shopify-api-js` [here](https://github.com/Shopify/shopify-api-js/pull/1036), and we would like to make it available to Rails apps in the future as well.
Unit tests are provided in the PR to cover the new method. This has also been tested internally for our app (POS channel)
> Introduce the token exchange API for fetching access tokens

- CHANGELOG.md
- docs/usage/webhooks.md
- lib/shopify_api/webhooks/handler.rb
- lib/shopify_api/webhooks/registration.rb
- lib/shopify_api/webhooks/registry.rb
- lib/shopify_api/webhooks/request.rb
- test/test_helpers/fake_webhook_handler.rb
- test/test_helpers/new_fake_webhook_handler.rb
- test/webhooks/registry_test.rb
Fixes #1247 
Shopify recommends as a [best practice](https://shopify.dev/docs/apps/webhooks/best-practices#ignore-duplicates) to check the `x-shopify-webhook-id` to verify you are not processing duplicate webhooks. We currently are not passing this information into the webhook handler. This PR will add the webhook_id and api_version to the webhook handler to bring the ruby library in line with the Javascript library in terms of information the handler has access to.
This could be resolved in a couple of approaches outlined below
This is what is currently implemented in this PR.
The `webhook_id` and `api_version` are added to the webhook request object from the headers. They are then explicitly passed to the handle function.
This would be a breaking change, but would be a straightforward …
> Add webhook _id and api_version to webhook handler

- CHANGELOG.md
- docs/usage/rest.md
- lib/shopify_api/rest/base.rb
- lib/shopify_api/utils/attributes_comparator.rb
- test/clients/base_rest_resource_test.rb
- test/utils/attributes_comparator_test.rb
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1203
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1164
- Attempt to use url params as required keys in api body payload.
- Updates hash diff logic to submit updated values instead of diff values.
- Unit tests
- Manual testing with use cases from https://github.com/Shopify/shopify-api-ruby/issues/1164 including assets, draft order line item, and order changes using this script
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
gem "minitest"
gem 'shopify_api', path: '../src/github.com/Shopify/shopify-api-ruby'
gem "pry-byebug"
end
require "minitest/autorun"
require "shopify_api"
require "pry-byebug"
class PutResourceTest < Minitest::Test
def setup
access_token = ''
shop = '.myshopify.com' …
```
> Adds attributes comparator and test case

- CHANGELOG.md
- docs/usage/rest.md
- lib/shopify_api/rest/base.rb
- test/clients/base_rest_resource_test.rb
I've added a new attribute, `ShopifyAPI::Rest::Base.headers`, that can be used to set headers that will be sent with every request made by the resource through methods like `all`, `delete`, etc...
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1211
I've added an automated test for `all`.
> Allow adding custom headers in REST Resource HTTP calls

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
We want to be able to solve as many problems as possible, and help unblock developers. However, when we get duplicate / hard to reproduce issues, it takes away from the time we could be spending fixing them.
Revamping the issue template to suggest some things developers can check before opening an issue to see if a solution has been found, or to ensure we're getting as much context as we can, which really makes it easier for us to solve issues.
> Improve issue template

- docs/usage/webhooks.md
I updated my repositories to use the new webhook handler, but the documentation was slightly wrong.
- The `data` param is passed by name not position ([source](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/webhooks/handler.rb#L35)).
- Use the new module rather than the old one ([deprecation](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/webhooks/registry.rb#L202-L203)).
> Update webhooks documentation

- CHANGELOG.md
- lib/shopify_api/auth/jwt_payload.rb
- test/auth/jwt_payload_test.rb
Right now we specify a leeway of 10 seconds when validating JWT payload expiration, but no leeway for `nbf` (not valid before). The `shopify-api` JS [library](https://github.com/Shopify/shopify-app-js/blob/0fd6a80c0af45138240b6b508210d3ef6b9292ee/packages/apps/shopify-api/lib/session/decode-session-token.ts#L25C11-L25C25) does allow for `clockTolerance` in both fields, and I think it makes sense for the Ruby gem to do the same.
I added unit tests.
> Use same leeway for `exp` and `nbf` when parsing JWT

- CHANGELOG.md
- lib/shopify_api/rest/resources/2022_04/shop.rb
- lib/shopify_api/rest/resources/2022_07/shop.rb
- lib/shopify_api/rest/resources/2022_10/shop.rb
- lib/shopify_api/rest/resources/2023_01/shop.rb
- lib/shopify_api/rest/resources/2023_04/shop.rb
- lib/shopify_api/rest/resources/2023_07/shop.rb
- lib/shopify_api/rest/resources/2023_10/shop.rb
- lib/shopify_api/rest/resources/2024_01/shop.rb
- lib/shopify_api/rest/resources/2024_04/shop.rb
Fixes #1271 
The `tax_shipping` field will be `null` on newly created stores. `true` when enabled and `false` when subsequently disabled.
* Tested in a development app
> Update the shop.tax_shipping type

- docs/usage/custom_apps.md
Fixes https://github.com/Shopify/shopify-api-ruby/issues/1329
- Adds graphql client example with api version
- Adds REST api version setting example
Script for graphql admin client with api version
```ruby
require "shopify_api"
access_token = "shpat"
shop = "test.myshopify.com"
query = <<~QUERY
{
products(first: 10) {
edges {
cursor
node {
id
title
onlineStoreUrl
}
}
}
}
QUERY
session = ShopifyAPI::Auth::Session.new(
shop: shop,
access_token:
)
graphql_client = ShopifyAPI::Clients::Graphql::Admin.new(session: session, api_version: "unstable")
response = graphql_client.query(query: query)
puts response.body['data']
```
Script for REST
```ruby
require "shopify_api"
access_token = "shpat"
shop = "test.myshopify.com"
session = ShopifyAPI::Auth::Session.new(
shop: shop,
access_token:
) …
```
> Adds api version configuration example for custom app

- CHANGELOG.md
- lib/shopify_api/rest/base.rb
- sorbet/rbi/shims/hash.rb
Tackling issue #1296 Added indifferent access to create_instances_from_response in the ShopifyAPI::Rest::Base class.
> Adding indifferent access

- CHANGELOG.md
- docs/usage/rest.md
- lib/shopify_api/clients/rest/admin.rb
- lib/shopify_api/context.rb
- lib/shopify_api/errors/disabled_resource_error.rb
- test/clients/base_rest_resource_test.rb
- test/clients/rest/admin_test.rb
- test/context_test.rb
Fixes [Disable REST client for new apps](https://github.com/Shopify/first-party-library-planning/issues/694)
* We want new apps created with the Ruby template to use the GraphQL API, and not the REST API
* After this is released we will enable this config option in the template
* By default this is false, apps currently using the REST API will not be affected
* If the config option is true, an error will be raised if REST client is used.
* Tested in a local development app.
https://github.com/user-attachments/assets/b589ca06-c084-4a86-af69-9161f9d08904
> Add config option to disable the REST client

- CHANGELOG.md
- lib/shopify_api/auth/oauth.rb
- lib/shopify_api/clients/http_client.rb
Fixes https://github.com/Shopify/shop-server/issues/101259
In this PR, we add support for new Shopify internal hosts by rewriting the host to a generic one and passing the storefront domain as a `X-Forwarded-Host`. This change enables the installation of Shopify Apps, internally, in development.
We only filter on Shopify internal local development hosts so impact should be null in any other situation.
This was successfully tested. Please check the testing instructions in the linked issue.
> Support internal Shopify hosts

- CHANGELOG.md
- lib/shopify_api/auth/oauth.rb
When using DevServer, it can't find the admin url correctly
This PR fixes that
> Update oauth logic to account for new admin-web url
